// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6j_bF0Ud4ntxA_jAL9qszbxSsCDVXj94',
    appId: '1:773443264958:web:8115176f295ab33ad459ef',
    messagingSenderId: '773443264958',
    projectId: 'worksout-e9896',
    authDomain: 'worksout-e9896.firebaseapp.com',
    storageBucket: 'worksout-e9896.appspot.com',
    measurementId: 'G-8M7SY3FLVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMgeBdggPayZm8JdYOnOZrVgEpRqviQT8',
    appId: '1:773443264958:android:8df8292a9c8726e0d459ef',
    messagingSenderId: '773443264958',
    projectId: 'worksout-e9896',
    storageBucket: 'worksout-e9896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbGVoQxMsAF1YQsFd7ina1oORiscfLBY',
    appId: '1:773443264958:ios:da2b8bc95f57f58ad459ef',
    messagingSenderId: '773443264958',
    projectId: 'worksout-e9896',
    storageBucket: 'worksout-e9896.appspot.com',
    iosClientId: '773443264958-nvcf4vmdjf6n4ovft4eaggkh0trbm8e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.worksOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbGVoQxMsAF1YQsFd7ina1oORiscfLBY',
    appId: '1:773443264958:ios:ab0afbc7c4ef85c7d459ef',
    messagingSenderId: '773443264958',
    projectId: 'worksout-e9896',
    storageBucket: 'worksout-e9896.appspot.com',
    iosClientId: '773443264958-ka1lhjae7869lm9jh06j7pekbceg8jr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.worksOut.RunnerTests',
  );
}
